# Generated by Django 5.2.6 on 2025-09-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='statics/media/blog_default_pic.jpg', null=True, upload_to='media'),
        ),
    ]
